# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 22))
        self.menubar.setObjectName("menubar")
        self.menuPyshine = QtWidgets.QMenu(self.menubar)
        self.menuPyshine.setObjectName("menuPyshine")
        self.menuSubmenu = QtWidgets.QMenu(self.menuPyshine)
        self.menuSubmenu.setObjectName("menuSubmenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Layout-responsivo/Images/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionitem1 = QtWidgets.QAction(MainWindow)
        self.actionitem1.setObjectName("actionitem1")
        self.actionitem_2 = QtWidgets.QAction(MainWindow)
        self.actionitem_2.setObjectName("actionitem_2")
        self.menuSubmenu.addAction(self.actionitem1)
        self.menuSubmenu.addAction(self.actionitem_2)
        self.menuPyshine.addAction(self.actionNew)
        self.menuPyshine.addAction(self.actionExit)
        self.menuPyshine.addAction(self.menuSubmenu.menuAction())
        self.menubar.addAction(self.menuPyshine.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuPyshine.setTitle(_translate("MainWindow", "Pyshine"))
        self.menuSubmenu.setTitle(_translate("MainWindow", "Submenu"))
        self.statusbar.setStatusTip(_translate("MainWindow", "Pyshine"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionitem1.setText(_translate("MainWindow", "item1"))
        self.actionitem_2.setText(_translate("MainWindow", "item2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
